### ISSUE TITLE
Patched Geant4 and NuG4 UPS products for NOvA

### ISSUE THREAD

**Issue by vhewes** [NuSoftHEP/nug4#6]
NOvA recently upgraded to Geant4.11, and discovered a bug affecting several Geant4 EM processes that leads to race conditions in our simulation. We've created a patch for this bug, and confirmed that it fixes the race condition in our simulation by testing with a local Geant4 release. We'd like to request a new Geant4 UPS product (`v4_11_0_p03b`) with [this patch](https://github.com/NuSoftHEP/nug4/files/11315117/em-instance-counter.patch)  included, and a new NuG4 product (`v1_14_02`) built against it.

Please let me know if there's any other information you need, or if this isn't the appropriate place to request a new UPS product. Thank you!

**Comment by lgarren** [comment]
We are still using redmine issues for ups product requests.  
See https://cdcvs.fnal.gov/redmine/projects/cet-is/issues/new
Sorry for my confusion.  The patch is for geant4.

**Comment by vhewes** [comment]
OK great, thanks! I submitted a corresponding issue on redmine [here](https://cdcvs.fnal.gov/redmine/issues/28008).

**Comment by lgarren** [comment]
Done - see the redmine issue.
